'use strict';
// =====================================================================
//  SELEÇÕES — 50 seleções com os craques reais (outubro de 2026)
//  "craques": nomes de jogadores que já estão nos clubes do jogo.
//  "extras": craques de ligas que não estão no jogo (só existem na seleção).
//  O resto da convocação é completado com jogadores gerados.
// =====================================================================
const NACOES = [
    { id: 'BRA', nome: 'Brasil', bandeira: '🇧🇷', confed: 'CONMEBOL', forca: 87, c1: '#ffdf00', c2: '#009c3b', sigla: 'BRA', nomes: 'br',
        craques: `Alisson,Éderson,Marquinhos,Gabriel Magalhães,Éder Militão,Alexsandro Ribeiro,Danilo,Wesley,Alex Sandro,Casemiro,Bruno Guimarães,André,Paquetá,Andreas Pereira,Raphinha,Vinícius Júnior,Rodrygo,Estêvão,Gabriel Martinelli,Matheus Cunha,João Pedro,Endrick,Igor Jesus,Luiz Henrique,Savinho,Neymar,Richarlison`,
        extras: `Ederson:GOL:33:83,Bento:GOL:27:78,Douglas Santos:LAT:32:76` },
    { id: 'ARG', nome: 'Argentina', bandeira: '🇦🇷', confed: 'CONMEBOL', forca: 88, c1: '#75aadb', c2: '#ffffff', sigla: 'ARG', nomes: 'ar',
        craques: `Emiliano Martínez,Gerónimo Rulli,Walter Benítez,Cristian Romero,Lisandro Martínez,Nicolás Otamendi,Leonardo Balerdi,Nahuel Molina,Gonzalo Montiel,Nicolás Tagliafico,Facundo Medina,Enzo Fernández,Alexis Mac Allister,Rodrigo De Paul,Leandro Paredes,Giovani Lo Celso,Exequiel Palacios,Nico Paz,Thiago Almada,Franco Mastantuono,Lionel Messi,Lautaro Martínez,Julián Álvarez,Giuliano Simeone,Alejandro Garnacho`,
        extras: `Nicolás González:PON:28:79,Valentín Carboni:MEI:21:74` },
    { id: 'URU', nome: 'Uruguai', bandeira: '🇺🇾', confed: 'CONMEBOL', forca: 82, c1: '#5cb8e4', c2: '#ffffff', sigla: 'URU', nomes: 'ar',
        craques: `Rochet,Santiago Mele,Ronald Araújo,Mathías Olivera,Varela,Federico Valverde,Manuel Ugarte,Rodrigo Bentancur,Arrascaeta,Brian Rodríguez`,
        extras: `José María Giménez:ZAG:31:82,Nahitan Nández:VOL:30:76,Facundo Pellistri:PON:24:74,Maximiliano Araújo:LAT:26:77,Darwin Núñez:ATA:27:80,Rodrigo Aguirre:ATA:31:74` },
    { id: 'COL', nome: 'Colômbia', bandeira: '🇨🇴', confed: 'CONMEBOL', forca: 81, c1: '#fcd116', c2: '#003893', sigla: 'COL', nomes: 'es',
        craques: `Camilo Vargas,Jhon Lucumí,Daniel Muñoz,Johan Mojica,Jefferson Lerma,Kevin Castaño,Jhon Arias,Luis Díaz,Luis Suárez,Rafael Santos Borré`,
        extras: `Davinson Sánchez:ZAG:30:78,Richard Ríos:VOL:26:79,James Rodríguez:MEI:35:76,Jhon Córdoba:ATA:33:76,Jhon Durán:ATA:22:78` },
    { id: 'EQU', nome: 'Equador', bandeira: '🇪🇨', confed: 'CONMEBOL', forca: 79, c1: '#ffdd00', c2: '#034ea2', sigla: 'EQU', nomes: 'es',
        craques: `Hernán Galíndez,Piero Hincapié,Willian Pacho,Pervis Estupiñán,Félix Torres,Moisés Caicedo,Alan Franco,Enner Valencia,Jordy Caicedo,John Yeboah,Pedro Vite`,
        extras: `Moisés Ramírez:GOL:26:73,Kendry Páez:MEI:19:74,Gonzalo Plata:PON:26:76,Kevin Rodríguez:ATA:26:72` },
    { id: 'PAR', nome: 'Paraguai', bandeira: '🇵🇾', confed: 'CONMEBOL', forca: 77, c1: '#d52b1e', c2: '#ffffff', sigla: 'PAR', nomes: 'es',
        craques: `Gustavo Gómez,Omar Alderete,Balbuena,Júnior Alonso,Diego Gómez,Andrés Cubas,Miguel Almirón,Ramón Sosa,Antonio Sanabria,Gabriel Ávalos,Ángel Romero`,
        extras: `Gatito Fernández:GOL:38:72,Juan José Cáceres:LAT:26:72,Julio Enciso:MEI:22:77` },
    { id: 'CHI', nome: 'Chile', bandeira: '🇨🇱', confed: 'CONMEBOL', forca: 74, c1: '#d52b1e', c2: '#0039a6', sigla: 'CHI', nomes: 'es',
        craques: `Paulo Díaz,Gabriel Suazo,Pulgar,Rodrigo Echeverría,Alexis Sánchez`,
        extras: `Brayan Cortés:GOL:31:72,Guillermo Maripán:ZAG:32:75,Arturo Vidal:VOL:39:72,Darío Osorio:PON:22:74,Víctor Dávila:ATA:29:73,Ben Brereton Díaz:ATA:27:72` },
    { id: 'PER', nome: 'Peru', bandeira: '🇵🇪', confed: 'CONMEBOL', forca: 72, c1: '#ffffff', c2: '#d91023', sigla: 'PER', nomes: 'es',
        craques: `Luis Advíncula,André Carrillo`,
        extras: `Pedro Gallese:GOL:36:72,Carlos Zambrano:ZAG:37:68,Alexander Callens:ZAG:34:70,Renato Tapia:VOL:31:73,Piero Quispe:MEI:25:72,Edison Flores:MEI:32:70,Paolo Guerrero:ATA:42:66,Gianluca Lapadula:ATA:36:70` },
    { id: 'FRA', nome: 'França', bandeira: '🇫🇷', confed: 'UEFA', forca: 88, c1: '#002654', c2: '#ffffff', sigla: 'FRA', nomes: 'fr',
        craques: `Mike Maignan,Brice Samba,Lucas Chevalier,William Saliba,Dayot Upamecano,Ibrahima Konaté,Jules Koundé,Lucas Hernández,Malo Gusto,Lucas Digne,Aurélien Tchouaméni,Eduardo Camavinga,Adrien Rabiot,Warren Zaïre-Emery,Manu Koné,Michael Olise,Ousmane Dembélé,Désiré Doué,Bradley Barcola,Kylian Mbappé,Hugo Ekitike,Marcus Thuram,Randal Kolo Muani,Rayan Cherki`,
        extras: `Theo Hernández:LAT:29:83,N'Golo Kanté:VOL:35:80,Kingsley Coman:PON:30:80` },
    { id: 'ESP', nome: 'Espanha', bandeira: '🇪🇸', confed: 'UEFA', forca: 89, c1: '#c60b1e', c2: '#ffc400', sigla: 'ESP', nomes: 'es',
        craques: `Unai Simón,David Raya,Álex Remiro,Robin Le Normand,Dean Huijsen,Pau Cubarsí,Pedro Porro,Marc Cucurella,Alejandro Grimaldo,Rodri,Pedri,Gavi,Fabián Ruiz,Martín Zubimendi,Mikel Merino,Dani Olmo,Lamine Yamal,Nico Williams,Ferran Torres,Mikel Oyarzabal,Álvaro Morata,Yéremy Pino,Álex Baena`,
        extras: `Aymeric Laporte:ZAG:32:81,Dani Carvajal:LAT:34:81,Samu Aghehowa:ATA:22:79` },
    { id: 'ENG', nome: 'Inglaterra', bandeira: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', confed: 'UEFA', forca: 87, c1: '#ffffff', c2: '#1d3b8a', sigla: 'ENG', nomes: 'en',
        craques: `Jordan Pickford,Aaron Ramsdale,Dean Henderson,John Stones,Marc Guéhi,Ezri Konsa,Levi Colwill,Trent Alexander-Arnold,Reece James,Kyle Walker,Myles Lewis-Skelly,Declan Rice,Jude Bellingham,Kobbie Mainoo,Elliot Anderson,Morgan Rogers,Phil Foden,Cole Palmer,Bukayo Saka,Anthony Gordon,Jarrod Bowen,Eberechi Eze,Harry Kane,Ollie Watkins,Dominic Solanke`,
        extras: `Marcus Rashford:PON:29:80,Ivan Toney:ATA:30:79` },
    { id: 'GER', nome: 'Alemanha', bandeira: '🇩🇪', confed: 'UEFA', forca: 85, c1: '#ffffff', c2: '#000000', sigla: 'GER', nomes: 'de',
        craques: `Marc-André ter Stegen,Oliver Baumann,Alexander Nübel,Antonio Rüdiger,Jonathan Tah,Nico Schlotterbeck,Waldemar Anton,Joshua Kimmich,David Raum,Maximilian Mittelstädt,Robert Andrich,Aleksandar Pavlović,Leon Goretzka,Florian Wirtz,Jamal Musiala,Kai Havertz,Serge Gnabry,Karim Adeyemi,Nick Woltemade,Tim Kleindienst,Deniz Undav`,
        extras: `Leroy Sané:PON:30:82,Niclas Füllkrug:ATA:33:75` },
    { id: 'POR', nome: 'Portugal', bandeira: '🇵🇹', confed: 'UEFA', forca: 86, c1: '#c8102e', c2: '#006600', sigla: 'POR', nomes: 'pt',
        craques: `José Sá,Rúben Dias,Renato Veiga,João Cancelo,Nuno Mendes,Diogo Dalot,Vitinha,João Neves,Bruno Fernandes,Bernardo Silva,João Palhinha,Rafael Leão,Pedro Neto,Francisco Conceição,Gonçalo Ramos`,
        extras: `Diogo Costa:GOL:27:84,António Silva:ZAG:23:80,Gonçalo Inácio:ZAG:25:81,Nélson Semedo:LAT:33:77,Rúben Neves:VOL:29:80,Francisco Trincão:PON:26:80,Cristiano Ronaldo:ATA:41:82,João Félix:MEI:27:79` },
    { id: 'NED', nome: 'Holanda', bandeira: '🇳🇱', confed: 'UEFA', forca: 84, c1: '#f36c21', c2: '#ffffff', sigla: 'NED', nomes: 'nl',
        craques: `Bart Verbruggen,Mark Flekken,Virgil van Dijk,Matthijs de Ligt,Micky van de Ven,Jurriën Timber,Denzel Dumfries,Jeremie Frimpong,Frenkie de Jong,Ryan Gravenberch,Teun Koopmeiners,Xavi Simons,Cody Gakpo,Memphis Depay,Donyell Malen,Brian Brobbey,Justin Kluivert`,
        extras: `Nathan Aké:ZAG:31:80,Tijjani Reijnders:MEI:28:84` },
    { id: 'ITA', nome: 'Itália', bandeira: '🇮🇹', confed: 'UEFA', forca: 83, c1: '#0066b3', c2: '#ffffff', sigla: 'ITA', nomes: 'it',
        craques: `Gianluigi Donnarumma,Guglielmo Vicario,Alex Meret,Alessandro Bastoni,Riccardo Calafiori,Alessandro Buongiorno,Giovanni Di Lorenzo,Federico Gatti,Destiny Udogie,Andrea Cambiaso,Federico Dimarco,Sandro Tonali,Nicolò Barella,Davide Frattesi,Samuele Ricci,Manuel Locatelli,Nicolò Fagioli,Moise Kean,Giacomo Raspadori,Federico Chiesa,Lorenzo Lucca,Francesco Pio Esposito`,
        extras: `Mateo Retegui:ATA:27:80` },
    { id: 'BEL', nome: 'Bélgica', bandeira: '🇧🇪', confed: 'UEFA', forca: 82, c1: '#e30613', c2: '#000000', sigla: 'BEL', nomes: 'nl',
        craques: `Thibaut Courtois,Arthur Theate,Wout Faes,Timothy Castagne,Maxim De Cuyper,Amadou Onana,Youri Tielemans,Kevin De Bruyne,Jérémy Doku,Johan Bakayoko,Charles De Ketelaere,Loïs Openda`,
        extras: `Koen Casteels:GOL:34:78,Zeno Debast:ZAG:23:77,Leandro Trossard:PON:31:80,Romelu Lukaku:ATA:33:80,Dodi Lukébakio:PON:28:77` },
    { id: 'CRO', nome: 'Croácia', bandeira: '🇭🇷', confed: 'UEFA', forca: 81, c1: '#ff0000', c2: '#ffffff', sigla: 'CRO', nomes: 'bal',
        craques: `Dominik Livaković,Joško Gvardiol,Duje Ćaleta-Car,Josip Stanišić,Luka Modrić,Mateo Kovačić,Lovro Majer,Martin Baturina,Mario Pašalić,Luka Sučić,Ivan Perišić,Andrej Kramarić,Ante Budimir,Petar Sučić`,
        extras: `` },
    { id: 'SUI', nome: 'Suíça', bandeira: '🇨🇭', confed: 'UEFA', forca: 79, c1: '#ff0000', c2: '#ffffff', sigla: 'SUI', nomes: 'de',
        craques: `Gregor Kobel,Manuel Akanji,Nico Elvedi,Ricardo Rodríguez,Silvan Widmer,Granit Xhaka,Denis Zakaria,Dan Ndoye,Rubén Vargas,Breel Embolo`,
        extras: `Yann Sommer:GOL:37:79,Remo Freuler:VOL:34:76,Fabian Rieder:MEI:24:74,Zeki Amdouni:ATA:25:74` },
    { id: 'DEN', nome: 'Dinamarca', bandeira: '🇩🇰', confed: 'UEFA', forca: 80, c1: '#c8102e', c2: '#ffffff', sigla: 'DEN', nomes: 'nor',
        craques: `Mads Hermansen,Joachim Andersen,Andreas Christensen,Victor Kristiansen,Pierre-Emile Højbjerg,Morten Hjulmand,Christian Eriksen,Mikkel Damsgaard,Rasmus Højlund,Jonas Wind,Gustav Isaksen`,
        extras: `Kasper Schmeichel:GOL:39:76` },
    { id: 'NOR', nome: 'Noruega', bandeira: '🇳🇴', confed: 'UEFA', forca: 80, c1: '#ba0c2f', c2: '#ffffff', sigla: 'NOR', nomes: 'nor',
        craques: `Ørjan Nyland,Kristoffer Ajer,Leo Østigård,Julian Ryerson,Martin Ødegaard,Sander Berge,Antonio Nusa,Oscar Bobb,Erling Haaland,Alexander Sørloth,Jørgen Strand Larsen`,
        extras: `` },
    { id: 'AUT', nome: 'Áustria', bandeira: '🇦🇹', confed: 'UEFA', forca: 78, c1: '#ed2939', c2: '#ffffff', sigla: 'AUT', nomes: 'de',
        craques: `Kevin Danso,Konrad Laimer,Nicolas Seiwald,Marcel Sabitzer,Christoph Baumgartner,Michael Gregoritsch`,
        extras: `Patrick Pentz:GOL:29:74,David Alaba:ZAG:34:79,Philipp Mwene:LAT:32:73,Xaver Schlager:VOL:28:78,Marko Arnautović:ATA:37:74` },
    { id: 'TUR', nome: 'Turquia', bandeira: '🇹🇷', confed: 'UEFA', forca: 79, c1: '#e30a17', c2: '#ffffff', sigla: 'TUR', nomes: 'tr',
        craques: `Ferdi Kadıoğlu,Hakan Çalhanoğlu,Arda Güler,Kenan Yıldız,Can Uzun`,
        extras: `Uğurcan Çakır:GOL:30:79,Merih Demiral:ZAG:28:79,Abdülkerim Bardakcı:ZAG:31:77,Orkun Kökçü:MEI:25:80,Kerem Aktürkoğlu:PON:27:79,Barış Alper Yılmaz:PON:26:79` },
    { id: 'POL', nome: 'Polônia', bandeira: '🇵🇱', confed: 'UEFA', forca: 76, c1: '#ffffff', c2: '#dc143c', sigla: 'POL', nomes: 'pl',
        craques: `Wojciech Szczęsny,Łukasz Skorupski,Matty Cash,Piotr Zieliński,Sebastian Szymański,Nicola Zalewski,Robert Lewandowski`,
        extras: `Jan Bednarek:ZAG:30:76,Jakub Kiwior:ZAG:26:77,Krzysztof Piątek:ATA:31:74` },
    { id: 'SRB', nome: 'Sérvia', bandeira: '🇷🇸', confed: 'UEFA', forca: 77, c1: '#c6363c', c2: '#ffffff', sigla: 'SRB', nomes: 'bal',
        craques: `Strahinja Pavlović,Nikola Milenković,Saša Lukić,Lazar Samardžić`,
        extras: `Predrag Rajković:GOL:30:76,Sergej Milinković-Savić:MEI:31:80,Dušan Tadić:MEI:37:75,Dušan Vlahović:ATA:26:82,Aleksandar Mitrović:ATA:31:78` },
    { id: 'SCO', nome: 'Escócia', bandeira: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', confed: 'UEFA', forca: 75, c1: '#0065bf', c2: '#ffffff', sigla: 'SCO', nomes: 'en',
        craques: `Angus Gunn,Andy Robertson,Scott McTominay,John McGinn,Billy Gilmour,Ché Adams`,
        extras: `Kieran Tierney:LAT:29:76,Lyndon Dykes:ATA:31:70` },
    { id: 'SWE', nome: 'Suécia', bandeira: '🇸🇪', confed: 'UEFA', forca: 78, c1: '#fecc00', c2: '#006aa7', sigla: 'SWE', nomes: 'nor',
        craques: `Victor Lindelöf,Isak Hien,Gabriel Gudmundsson,Lucas Bergvall,Yasin Ayari,Anthony Elanga,Viktor Gyökeres,Alexander Isak`,
        extras: `Robin Olsen:GOL:36:72,Dejan Kulusevski:MEI:26:82` },
    { id: 'USA', nome: 'Estados Unidos', bandeira: '🇺🇸', confed: 'CONCACAF', forca: 79, c1: '#ffffff', c2: '#0a3161', sigla: 'USA', nomes: 'en',
        craques: `Matt Turner,Matt Freese,Chris Richards,Tim Ream,Antonee Robinson,Sergiño Dest,Tyler Adams,Weston McKennie,Yunus Musah,Giovanni Reyna,Christian Pulisic,Timothy Weah,Folarin Balogun,Ricardo Pepi,Josh Sargent,Malik Tillman,Diego Luna`,
        extras: `` },
    { id: 'MEX', nome: 'México', bandeira: '🇲🇽', confed: 'CONCACAF', forca: 78, c1: '#006847', c2: '#ffffff', sigla: 'MEX', nomes: 'es',
        craques: `Luis Ángel Malagón,Raúl Rangel,Johan Vásquez,Jesús Gallardo,Luis Romo,Erick Sánchez,Alexis Vega,Raúl Jiménez,Roberto Alvarado`,
        extras: `Guillermo Ochoa:GOL:41:72,César Montes:ZAG:29:76,Jorge Sánchez:LAT:29:74,Edson Álvarez:VOL:28:79,Luis Chávez:MEI:30:75,Orbelín Pineda:MEI:30:74,Hirving Lozano:PON:31:76,Santiago Giménez:ATA:25:80,Julián Quiñones:ATA:29:76` },
    { id: 'CAN', nome: 'Canadá', bandeira: '🇨🇦', confed: 'CONCACAF', forca: 76, c1: '#ff0000', c2: '#ffffff', sigla: 'CAN', nomes: 'en',
        craques: `Maxime Crépeau,Dayne St. Clair,Moïse Bombito,Derek Cornelius,Alphonso Davies,Ismaël Koné,Jonathan Osorio,Tajon Buchanan,Jonathan David,Jacob Shaffelburg`,
        extras: `Alistair Johnston:LAT:28:75,Stephen Eustáquio:VOL:30:77,Cyle Larin:ATA:31:73` },
    { id: 'CRC', nome: 'Costa Rica', bandeira: '🇨🇷', confed: 'CONCACAF', forca: 70, c1: '#ce1126', c2: '#002b7f', sigla: 'CRC', nomes: 'es',
        craques: `Keylor Navas`,
        extras: `Francisco Calvo:ZAG:34:70,Joel Campbell:PON:34:70,Manfred Ugalde:ATA:24:73,Brandon Aguilera:MEI:23:70,Orlando Galo:MEI:26:68` },
    { id: 'PAN', nome: 'Panamá', bandeira: '🇵🇦', confed: 'CONCACAF', forca: 70, c1: '#da121a', c2: '#ffffff', sigla: 'PAN', nomes: 'es',
        craques: `Adalberto Carrasquilla`,
        extras: `Orlando Mosquera:GOL:32:68,Fidel Escobar:ZAG:31:70,Michael Amir Murillo:LAT:30:73,Ismael Díaz:ATA:29:70,José Fajardo:ATA:32:68,Cecilio Waterman:ATA:35:67` },
    { id: 'JAM', nome: 'Jamaica', bandeira: '🇯🇲', confed: 'CONCACAF', forca: 69, c1: '#fed100', c2: '#009b3a', sigla: 'JAM', nomes: 'en',
        craques: `Andre Blake,Ethan Pinnock,Demarai Gray`,
        extras: `Leon Bailey:PON:29:78,Bobby Decordova-Reid:MEI:33:72,Michail Antonio:ATA:36:72,Shamar Nicholson:ATA:29:70` },
    { id: 'MAR', nome: 'Marrocos', bandeira: '🇲🇦', confed: 'CAF', forca: 82, c1: '#c1272d', c2: '#006233', sigla: 'MAR', nomes: 'arab',
        craques: `Achraf Hakimi,Nayef Aguerd,Noussair Mazraoui,Sofyan Amrabat,Azzedine Ounahi,Bilal El Khannouss,Brahim Díaz,Abde Ezzalzouli,Eliesse Ben Seghir`,
        extras: `Yassine Bounou:GOL:35:82,Munir Mohamedi:GOL:37:73,Romain Saïss:ZAG:36:72,Hakim Ziyech:PON:33:76,Youssef En-Nesyri:ATA:29:79,Ayoub El Kaabi:ATA:33:77` },
    { id: 'SEN', nome: 'Senegal', bandeira: '🇸🇳', confed: 'CAF', forca: 79, c1: '#ffffff', c2: '#00853f', sigla: 'SEN', nomes: 'afr',
        craques: `Moussa Niakhaté,Pape Matar Sarr,Idrissa Gueye,Pape Gueye,Lamine Camara,Ismaïla Sarr,Iliman Ndiaye,Nicolas Jackson,Boulaye Dia,Habib Diarra`,
        extras: `Édouard Mendy:GOL:34:79,Kalidou Koulibaly:ZAG:35:79,Abdou Diallo:ZAG:30:74,Sadio Mané:PON:34:80` },
    { id: 'NGA', nome: 'Nigéria', bandeira: '🇳🇬', confed: 'CAF', forca: 78, c1: '#008751', c2: '#ffffff', sigla: 'NGA', nomes: 'afr',
        craques: `Calvin Bassey,Ola Aina,Alex Iwobi,Samuel Chukwueze,Ademola Lookman,Victor Boniface,Moses Simon,Tolu Arokodare`,
        extras: `Stanley Nwabali:GOL:30:72,William Troost-Ekong:ZAG:33:74,Wilfred Ndidi:VOL:29:79,Frank Onyeka:VOL:28:74,Victor Osimhen:ATA:27:86` },
    { id: 'CIV', nome: 'Costa do Marfim', bandeira: '🇨🇮', confed: 'CAF', forca: 78, c1: '#ff8200', c2: '#009e60', sigla: 'CIV', nomes: 'afr',
        craques: `Odilon Kossounou,Evan Ndicka,Ibrahim Sangaré,Simon Adingra,Amad Diallo,Sébastien Haller,Nicolas Pépé`,
        extras: `Yahia Fofana:GOL:26:73,Wilfried Singo:LAT:25:77,Ghislain Konan:LAT:31:72,Franck Kessié:VOL:29:80,Seko Fofana:MEI:31:77,Oumar Diakité:PON:23:72` },
    { id: 'CMR', nome: 'Camarões', bandeira: '🇨🇲', confed: 'CAF', forca: 75, c1: '#007a5e', c2: '#ce1126', sigla: 'CMR', nomes: 'afr',
        craques: `Jean-Charles Castelletto,Christopher Wooh,Carlos Baleba,Bryan Mbeumo,Eric Maxim Choupo-Moting`,
        extras: `André Onana:GOL:30:80,Devis Epassy:GOL:33:70,André-Frank Zambo Anguissa:VOL:30:81,Vincent Aboubakar:ATA:34:74,Karl Toko Ekambi:PON:34:72` },
    { id: 'GHA', nome: 'Gana', bandeira: '🇬🇭', confed: 'CAF', forca: 75, c1: '#ffffff', c2: '#000000', sigla: 'GHA', nomes: 'afr',
        craques: `Mohammed Salisu,Mohammed Kudus,Antoine Semenyo,Jordan Ayew,Iñaki Williams,Ernest Nuamah`,
        extras: `Lawrence Ati-Zigi:GOL:30:71,Alexander Djiku:ZAG:32:74,Thomas Partey:VOL:33:79` },
    { id: 'EGY', nome: 'Egito', bandeira: '🇪🇬', confed: 'CAF', forca: 76, c1: '#ce1126', c2: '#ffffff', sigla: 'EGY', nomes: 'arab',
        craques: `Omar Marmoush,Mostafa Mohamed`,
        extras: `Mohamed El Shenawy:GOL:38:73,Mohamed Abdelmonem:ZAG:27:75,Mohamed Hany:LAT:30:71,Mohamed Salah:PON:34:87,Trézéguet:PON:32:73,Emam Ashour:MEI:28:74` },
    { id: 'ALG', nome: 'Argélia', bandeira: '🇩🇿', confed: 'CAF', forca: 76, c1: '#ffffff', c2: '#006233', sigla: 'ALG', nomes: 'arab',
        craques: `Aïssa Mandi,Ramy Bensebaini,Rayan Aït-Nouri,Amine Gouiri,Mohamed Amoura`,
        extras: `Anthony Mandrea:GOL:30:72,Ismaël Bennacer:VOL:28:78,Houssem Aouar:MEI:28:77,Riyad Mahrez:PON:35:79,Saïd Benrahma:PON:31:75` },
    { id: 'TUN', nome: 'Tunísia', bandeira: '🇹🇳', confed: 'CAF', forca: 72, c1: '#e70013', c2: '#ffffff', sigla: 'TUN', nomes: 'arab',
        craques: `Montassar Talbi,Ali Abdi,Ellyes Skhiri,Hannibal Mejbri`,
        extras: `Aymen Dahmen:GOL:29:70,Youssef Msakni:PON:36:70` },
    { id: 'JPN', nome: 'Japão', bandeira: '🇯🇵', confed: 'AFC', forca: 80, c1: '#000555', c2: '#ffffff', sigla: 'JPN', nomes: 'jp',
        craques: `Zion Suzuki,Ko Itakura,Hiroki Ito,Wataru Endo,Ao Tanaka,Daichi Kamada,Takefusa Kubo,Kaoru Mitoma,Ritsu Doan,Takumi Minamino,Ayase Ueda,Kyogo Furuhashi`,
        extras: `Takehiro Tomiyasu:ZAG:27:78,Hidemasa Morita:VOL:31:78,Junya Ito:PON:33:76` },
    { id: 'KOR', nome: 'Coreia do Sul', bandeira: '🇰🇷', confed: 'AFC', forca: 77, c1: '#c60c30', c2: '#ffffff', sigla: 'KOR', nomes: 'kr',
        craques: `Kim Min-jae,Hwang In-beom,Kang-in Lee,Lee Jae-sung,Hwang Hee-chan,Son Heung-min,Bae Jun-ho`,
        extras: `Jo Hyeon-woo:GOL:35:73,Seol Young-woo:LAT:28:73,Oh Hyeon-gyu:ATA:25:73` },
    { id: 'AUS', nome: 'Austrália', bandeira: '🇦🇺', confed: 'AFC', forca: 73, c1: '#ffcd00', c2: '#00843d', sigla: 'AUS', nomes: 'en',
        craques: `Mathew Ryan,Jackson Irvine,Riley McGree`,
        extras: `Harry Souttar:ZAG:28:74,Alessandro Circati:ZAG:23:73,Craig Goodwin:PON:34:70,Mitchell Duke:ATA:35:68` },
    { id: 'IRN', nome: 'Irã', bandeira: '🇮🇷', confed: 'AFC', forca: 73, c1: '#ffffff', c2: '#da0000', sigla: 'IRN', nomes: 'ir',
        craques: ``,
        extras: `Alireza Beiranvand:GOL:34:72,Shojae Khalilzadeh:ZAG:37:68,Saeid Ezatolahi:VOL:30:71,Saman Ghoddos:MEI:33:70,Alireza Jahanbakhsh:PON:33:71,Mehdi Taremi:ATA:34:77,Sardar Azmoun:ATA:31:76` },
    { id: 'KSA', nome: 'Arábia Saudita', bandeira: '🇸🇦', confed: 'AFC', forca: 71, c1: '#ffffff', c2: '#006c35', sigla: 'KSA', nomes: 'arab',
        craques: `Saud Abdulhamid`,
        extras: `Mohammed Al-Owais:GOL:35:72,Ali Al-Bulaihi:ZAG:37:68,Salem Al-Dawsari:PON:35:75,Firas Al-Buraikan:ATA:26:73,Saleh Al-Shehri:ATA:33:69` },
    { id: 'QAT', nome: 'Catar', bandeira: '🇶🇦', confed: 'AFC', forca: 70, c1: '#8a1538', c2: '#ffffff', sigla: 'QAT', nomes: 'arab',
        craques: ``,
        extras: `Meshaal Barsham:GOL:28:70,Pedro Miguel:ZAG:36:68,Akram Afif:PON:30:77,Almoez Ali:ATA:30:73,Hassan Al-Haydos:MEI:36:68` },
    { id: 'UZB', nome: 'Uzbequistão', bandeira: '🇺🇿', confed: 'AFC', forca: 69, c1: '#1eb53a', c2: '#ffffff', sigla: 'UZB', nomes: 'ir',
        craques: ``,
        extras: `` },
    { id: 'IRQ', nome: 'Iraque', bandeira: '🇮🇶', confed: 'AFC', forca: 68, c1: '#ffffff', c2: '#007a3d', sigla: 'IRQ', nomes: 'arab',
        craques: ``,
        extras: `` },
    { id: 'NZL', nome: 'Nova Zelândia', bandeira: '🇳🇿', confed: 'OFC', forca: 66, c1: '#ffffff', c2: '#000000', sigla: 'NZL', nomes: 'en',
        craques: `Michael Boxall,Liberato Cacace,Chris Wood`,
        extras: `Max Crocombe:GOL:33:68,Joe Bell:MEI:27:68,Marko Stamenić:MEI:24:70,Matt Garbett:MEI:24:68` },
];
